name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      my-tag:
        description: 'tag'
        required: true
        default: 'trigger001'
      
jobs:
  build-push-images:
    runs-on: ubuntu-latest
    container:
      image: node:16.19-alpine
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: install tools
        run: |
          apk add --no-cache bash git
          npm install -g pnpm@6.32.1 gulp@4.0.2
          apk add --no-cache openssh curl bash bind-tools zip docker
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin/kubectl
      
      - name: check out 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: set-git-config
        run: |
          cd /app
          git config --global --add safe.directory /app
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: build-test
        run: |
          cd /app
          pnpm i -r
          pnpm run test:ci

