name: CI

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - closed
  workflow_dispatch:
    inputs:
      my-tag:
        description: "tag"
        required: true
        default: "trigger test"

jobs:
  run-test:
    runs-on: ubuntu-latest
    container:
      image: node:16.19-alpine
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: install tools
        run: |
          apk add --no-cache bash git
          npm install -g pnpm@6.32.1 gulp@4.0.2
          apk add --no-cache openssh curl bash bind-tools zip docker
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin/kubectl

      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: set-git-config
        run: |
          cd /app
          git config --global --add safe.directory /app
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: install-packages
        run: |
          cd /app
          pnpm i -r

      - name: create-coveralls-config
        run: |
          cd /app
          echo "repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}" > .coveralls.yml
          ls /app/.coveralls.yml

      - name: start-test
        run: |
          cd /app
          pnpm run coverage
